from mtbot.okx.consts import *
from mtbot.side import LongSide, ShortSide

EXCHANGE = 'okx'
INST_ID = INST_BTC_USDT_SWAP
CANDLE_BAR_TYPE = BAR_1M

STRATEGY_MA_DURATION = 10
STRATEGY_MAX_REPO_SIZE = STRATEGY_MA_DURATION * 5

ORDER_POS_SIDE = ShortSide()
ORDER_START_POS = 10
ORDER_FOLLOW_RATE = .004
ORDER_PROFIT_STEP_RATE = .0002
ORDER_MAX_COUNT = 5
ORDER_POS_TYPE = TD_MODE_ISOLATE

FAILURE_THRESHOLD_CONFIRM = 10
FAILURE_THRESHOLD_PLACE_ALGO = 10
FAILURE_THRESHOLD_EXTRA_MARGIN = 10
